/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "emFile.h"
#include "UART.h"
#include "Yellow_aliases.h"
#include "Yellow.h"
#include "Green_aliases.h"
#include "Green.h"
#include "White_aliases.h"
#include "White.h"
#include "MCLK_aliases.h"
#include "MCLK.h"
#include "Audio_Interrupt.h"
#include "Audio_Timer.h"
#include "TestPin_aliases.h"
#include "TestPin.h"
#include "Clock_1.h"
#include "Clock_2.h"
#include "I2S.h"
#include "I2S_PVT.h"
#include "emFile_SPI0.h"
#include "emFile_SPI0_PVT.h"
#include "emFile_mosi0_aliases.h"
#include "emFile_mosi0.h"
#include "emFile_Clock_1.h"
#include "emFile_miso0_aliases.h"
#include "emFile_miso0.h"
#include "emFile_sclk0_aliases.h"
#include "emFile_sclk0.h"
#include "emFile_SPI0_CS_aliases.h"
#include "emFile_SPI0_CS.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

